// Code authored by Dean Edis (DeanTheCoder).
// Anyone is free to copy, modify, use, compile, or distribute this software,
// either in source code form or as a compiled binary, for any non-commercial
// purpose.
//
// If you modify the code, please retain this copyright header,
// and consider contributing back to the repository or letting us know
// about your modifications. Your contributions are valued!
//
// THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND.

using System.Text;
using AgentPrimer.Utilities;
using DTC.Core.Extensions;
using DTC.Core.Markdown;

namespace AgentPrimer;

/// <summary>
/// Renders repository reports and errors to the sb.
/// </summary>
internal sealed class ConsoleReportOutput
{
    public int WriteRepositoryNotFound()
    {
        Console.WriteLine("This script must be run from a git repository.");
        return 1;
    }

    public int WriteGitUnavailable()
    {
        Console.WriteLine("Git is not installed on this machine.");
        return 1;
    }

    public int WriteReport(PrimerReport report)
    {
        var sb = new StringBuilder();
        var consoleMarkdown = new ConsoleMarkdown();
        
        sb.AppendLine("# Repo Snapshot");
        sb.AppendLine("_Snapshot of the current repository and related projects, generated by [AgentPrimer](https://github.com/deanthecoder/AgentPrimer)._");
        sb.AppendLine("## Path");
        sb.AppendLine($"  `{report.RepositoryPath}`");

        if (report.Repositories.Count > 0)
        {
            sb.AppendLine($"## Repositories ({report.Repositories.Count})");
            foreach (var repository in report.Repositories)
            {
                sb.AppendLine($"  - {repository.Url} {(repository.IsSubmodule ? "(Submodule)" : string.Empty)}  ");
                sb.AppendLine($"    {repository.Description}  ");
            }
        }

        sb.AppendLine("## Stats");
        sb.AppendLine($"* Files      : {report.SourceFileCount}");

        if (report.LanguageBreakdown.Count == 0)
        {
            sb.AppendLine("* Languages  : none");
        }
        else
        {
            var languageSummary = report.LanguageBreakdown
                .Select(o => $"{o.Key} ({o.Value:P0})")
                .ToCsv()
                .Replace(",", " | ", StringComparison.Ordinal);

            sb.AppendLine($"* Languages  : {languageSummary}");
        }
        
        sb.AppendLine($"* English    : {report.EnglishPreference} English");

        sb.AppendLine($"## NuGet ({report.NugetPackages.Count})");
        if (report.NugetPackages.Count == 0)
        {
            sb.AppendLine("  none");
        }
        else
        {
            var names = report.NugetPackages
                .Select(i => $"`{i.Name}`")
                .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
                .ToArray();

            ConsoleSectionWriter.PrintWrappedList(sb, names, indent: "  ", maxWidth: 80, separator: " | ");
        }

        sb.AppendLine("## Preferences");
        if (report.NullableReferenceTypesEnabled.HasValue)
            sb.AppendLine($"* Nullable : {(report.NullableReferenceTypesEnabled.Value ? "enabled" : "disabled")}");
        if (report.UnitTestFramework.HasValue)
            sb.AppendLine($"* Tests    : {report.UnitTestFramework.Value}");
        if (report.MockingFramework.HasValue)
            sb.AppendLine($"* Mocking  : {report.MockingFramework.Value}");
        if (report.PreferredUiLibraries.Length > 0)
            sb.AppendLine($"* UI       : {report.PreferredUiLibraries.Select(o => o.ToString()).ToCsv(addSpace: true)}");

        if (report.InternalProjects.Count > 0)
        {
            var utilities = report.InternalProjects.Where(o => o.ReferenceCount > 0).ToArray();
            var topLevel = report.InternalProjects.Where(o => o.ReferenceCount == 0).ToArray();

            if (utilities.Length > 0 || topLevel.Length > 0)
            {
                sb.AppendLine("## Projects");
                if (topLevel.Length > 0)
                {
                    sb.AppendLine("### Top-level");
                    foreach (var project in topLevel)
                        sb.AppendLine($"* `{project.Name}` ({project.TargetFramework})");
                }

                if (utilities.Length > 0)
                {
                    sb.AppendLine("### Internal");
                    foreach (var library in utilities)
                        sb.AppendLine($"* `{library.Name}` ({library.TargetFramework}) [refs:{library.ReferenceCount}]");
                }
            }
        }

        if (report.ReadmeFiles.Count > 0)
        {
            sb.AppendLine($"## READMEs ({report.ReadmeFiles.Count})");
            foreach (var readme in report.ReadmeFiles)
                sb.AppendLine($"* `{readme}`");
        }

        consoleMarkdown.Write(sb.ToString());
        return 0;
    }
}
